### ISSUE TITLE
Upgrade from 0.20.0 to 0.21.0 stuck

### ISSUE THREAD

**Issue by jg-navas** [mariadb-operator/mariadb-operator-helm#10]
Hello there,

I have been using the operator in OpenStack since v0.11.0, and upgraded normally to v.0.20.0. However, when I tried to upgrade to v0.21.0 something has failed. This is the text of the error shown on the OpenShift console:

> error validating existing CRs against new CRD's schema for "mariadbs.mariadb.mmontes.io": error validating custom resource against new schema for MariaDB 1615-databases/mariadb: [].spec.image: Invalid value: "object": spec.image in body must be of type string: "object"

I do not know how to troubleshoot this issue. Also, I am not sure to send you any config files as I do not know which ones are relevant. Please advise on which parts of the configuration may be relevant so I can provide only what is necessary.

Perhaps it is some how relevant to point that OpenShift itself was recently upgraded from v4.10 to v4.12.

Thank you for your great work on this operator.

**Comment by melledouwsma** [comment]
This is kind of a duplicate of https://github.com/mariadb-operator/mariadb-operator/issues/257.

There are breaking changes in version v0.0.21 op the mariadb-operator. You can read more on the breaking changes in https://github.com/mariadb-operator/mariadb-operator/pull/248. The proposed upgrade path on https://github.com/mariadb-operator/mariadb-operator/blob/main/docs/UPGRADE_v0.0.21.md doesn't apply to this OLM managed operator, as the OLM also manages the CRD. It cannot upgrade the CRD as long as there are instances with the old syntax and you cannot update the syntax as long as the new version of the CRD is not present. It is a kind of circular dependency.

As a "workaround" I ended up uninstalling all MariaDB instances from the cluster, letting the upgrade succeed and then apply them again with the changed syntax. Please note that this approach will result in downtime or deleted data for the database instances.

**Comment by mmontes11** [comment]
> This is a duplicate of https://github.com/mariadb-operator/mariadb-operator/issues/257.

Indeed, this is a duplicate. Please, refer to this comment:
- https://github.com/mariadb-operator/mariadb-operator/issues/257#issuecomment-1795087998

**Comment by jg-navas** [comment]
Certainly, the referenced issue solves the issue.
Sorry for taking too long to close this one.
Thank you.
